apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-demo
data:
  index.html: |
    <h1>Hello from GitOps - Bai 4 - <span style="color:red">v2</span></h1>
    <p>Deploy by ArgoCD at 2026-04-29</p>