apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-demo
data:
  index.html: |
    <h6>Hello from GitOps - Bai 4.1 - <span style="color:red">v2</span></h6>
    <p>Deploy by ArgoCD at 2026-04-29</p>